language: ruby
rvm:
  - 2.3.0
cache: bundler
services:
  - postgresql

before_install:
  - gem update --system
  - gem --version
  - bundle install

before_script:
  - psql -c 'create database workdey_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar
  - java -jar selenium-server-standalone-2.43.1.jar
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - rake spec
bundler_args: --binstubs=./bundler_stubs
